export DATABASE_DRIVER="mysql+mysqlconnector"
export DATABASE_USERNAME="root"
export DATABASE_PASSWORD="Random_Password"
export DATABASE_HOST="localhost"
export DATABASE_PORT="3306"
export DATABASE_NAME="weather_db"