[tool.poetry]
name = "2-1-project"
version = "0.1.0"
description = "Transform, window, cross-correlate functions for using Python standard library."
authors = ["Domantas G"]
readme = "README.md"
packages = [{include = "turing_transforms", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
numpy = "^1.26.1"

[tool.poetry.group.dev.dependencies]
flake8 = "^6.1.0"
black = "^23.9.1"
isort = "^5.12.0"
mypy = "^1.5.1"
pytest = "^7.4.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
